name: Build DocxToRenpy

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade pip & Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow customtkinter

      - name: macOS extra dependencies
        if: matrix.os == 'macos-latest'
        run: |
          brew install tcl-tk

      - name: Run Release Script
        run: python release.py

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DocxToRenpy-${{ matrix.os }}
          path: |
            dist/*.zip
            dist/*.app
            dist/*.exe
