name: Build Releases

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pillow customtkinter

    - name: Run release script
      run: |
        python release.py

    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: DocxToRenpy-${{ matrix.os }}
        path: |
          dist/*.zip
          *.AppImage
